# Generated by Django 5.1.6 on 2025-04-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
