# Generated by Django 5.1.6 on 2025-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_journalentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
